version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/app
    command: air -c /usr/src/app/.air.toml
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - golang_api_network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - golang_api_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - golang_api_network

volumes:
  golang_api_data:

networks:
  golang_api_network:
